name: Deploy

on:
    workflow_run:
        workflows: ['CI']
        types: [completed]
  
jobs:

  build:

    runs-on: self-hosted

    steps:
    - name: Pull docker image
      run: sudo docker pull himanshudangwal/node-application:latest
    - name: Delete old container
      run: sudo docker rm -f node-continer || true
    - name: Start the new container
      run: sudo docker run -d -p 8080:8080 --name node-continer himanshudangwal/node-application

